### ISSUE TITLE
Wait option

### ISSUE THREAD

**Issue by feraudet** [bugcrowd/ecs-service-image-updater#16]
Hey,

It would be very cool to have an option to tell to ecs-service-image-updater to wait until the service reached a steady state.
AWS-SDK have this function : https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ECS.html#servicesStable-waiter

**Comment by ohookins** [comment]
Hi @feraudet, thanks for the issue. I think that's already covered by the other packages related to this one, for example https://github.com/bugcrowd/ecs-deployment-monitor
